from time import sleep
from userbot import CMD_HELP, bot
from userbot.events import register
from telethon import events
import asyncio


@register(outgoing=True, pattern="^.sayang$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("I LOVEE YOUUU 💕")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💗💕")
        await e.edit("💘💞💕💗")
        await e.edit("UPI SAYANG KAMU 💝💖💘")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💕💗")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("SELAMANYA 💕")
        await e.edit("💘💘💘💘")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("I LOVE YOUUUU")
        await e.edit("MWAAAAA")
        await e.edit("💕💞💘💝")
        await e.edit("💘💕💞💝")
        await e.edit("UPI SAYANG KAMU💞")


@register(outgoing=True, pattern='^.jamal(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`A A AWASS.....`")
    sleep(1)
    await typew.edit("`ADA JAMAL ANJING!!`")
    sleep(1)
    await typew.edit("`🏃                        🐕`")
    await typew.edit("`🏃                       🐕`")
    await typew.edit("`🏃                      🐕`")
    await typew.edit("`🏃                     🐕`")
    await typew.edit("`🏃   LUMPAT AJG       🐕`")
    await typew.edit("`🏃                   🐕`")
    await typew.edit("`🏃                  🐕`")
    await typew.edit("`🏃                 🐕`")
    await typew.edit("`🏃                🐕`")
    await typew.edit("`🏃 LARI AJG!     🐕`")
    await typew.edit("`🏃              🐕`")
    await typew.edit("`🏃             🐕`")
    await typew.edit("`🏃            🐕`")
    await typew.edit("`🏃           🐕`")
    await typew.edit("`🏃WOAH BABI!🐕`")
    await typew.edit("`🏃           🐕`")
    await typew.edit("`🏃            🐕`")
    await typew.edit("`🏃             🐕`")
    await typew.edit("`🏃              🐕`")
    await typew.edit("`🏃               🐕`")
    await typew.edit("`🏃    AJG AJG     🐕`")
    await typew.edit("`🏃                 🐕`")
    await typew.edit("`🏃                  🐕`")
    await typew.edit("`🏃                   🐕`")
    await typew.edit("`🏃                    🐕`")
    await typew.edit("`🏃                     🐕`")
    await typew.edit("`🏃  ANJING ANJING     🐕`")
    await typew.edit("`🏃                   🐕`")
    await typew.edit("`🏃                  🐕`")
    await typew.edit("`🏃                 🐕`")
    await typew.edit("`🏃                🐕`")
    await typew.edit("`🏃               🐕`")
    await typew.edit("`🏃              🐕`")
    await typew.edit("`🏃             🐕`")
    await typew.edit("`🏃            🐕`")
    await typew.edit("`🏃           🐕`")
    await typew.edit("`🏃          🐕`")
    await typew.edit("`🏃         🐕`")
    await typew.edit("`SI JAMAL MAKIN DEKET!!!`")
    sleep(1)
    await typew.edit("`🏃AAAAAAA🐕`")
    await typew.edit("`🏃AAAAAA🐕`")
    await typew.edit("`🏃AAAAA🐕`")
    await typew.edit("`🏃AAAA🐕`")
    await typew.edit("`Mati digigit si jamal`")


@register(outgoing=True, pattern='^.dimas(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`A A AWASS.....`")
    sleep(1)
    await typew.edit("`ADA DIMAS GONDRONG ANJING!!`")
    sleep(1)
    await typew.edit("`🏃                        🐕`")
    await typew.edit("`🏃                       🐕`")
    await typew.edit("`🏃                      🐕`")
    await typew.edit("`🏃                     🐕`")
    await typew.edit("`🏃   LUMPAT AJG       🐕`")
    await typew.edit("`🏃                   🐕`")
    await typew.edit("`🏃                  🐕`")
    await typew.edit("`🏃                 🐕`")
    await typew.edit("`🏃                🐕`")
    await typew.edit("`🏃 LARI AJG!     🐕`")
    await typew.edit("`🏃              🐕`")
    await typew.edit("`🏃             🐕`")
    await typew.edit("`🏃            🐕`")
    await typew.edit("`🏃           🐕`")
    await typew.edit("`🏃WOAH BABI!🐕`")
    await typew.edit("`🏃           🐕`")
    await typew.edit("`🏃            🐕`")
    await typew.edit("`🏃             🐕`")
    await typew.edit("`🏃              🐕`")
    await typew.edit("`🏃               🐕`")
    await typew.edit("`🏃    AJG AJG     🐕`")
    await typew.edit("`🏃                 🐕`")
    await typew.edit("`🏃                  🐕`")
    await typew.edit("`🏃                   🐕`")
    await typew.edit("`🏃                    🐕`")
    await typew.edit("`🏃                     🐕`")
    await typew.edit("`🏃  ANJING ANJING     🐕`")
    await typew.edit("`🏃                   🐕`")
    await typew.edit("`🏃                  🐕`")
    await typew.edit("`🏃                 🐕`")
    await typew.edit("`🏃                🐕`")
    await typew.edit("`🏃               🐕`")
    await typew.edit("`🏃              🐕`")
    await typew.edit("`🏃             🐕`")
    await typew.edit("`🏃            🐕`")
    await typew.edit("`🏃           🐕`")
    await typew.edit("`🏃          🐕`")
    await typew.edit("`🏃         🐕`")
    await typew.edit("`SI GONDRONG MAKIN DEKET!!!`")
    sleep(1)
    await typew.edit("`🏃AAAAAAA🐕`")
    await typew.edit("`🏃AAAAAA🐕`")
    await typew.edit("`🏃AAAAA🐕`")
    await typew.edit("`🏃AAAA🐕`")
    await typew.edit("`Mati digigit si gondrong`")


@register(outgoing=True, pattern="^.ngentot$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`DISINI NGENTOT`")
        await e.edit("`DISANA NGENTOT`")
        await e.edit("`DIMANA MANA KONTOL`")
        await e.edit("`KU NGENTOT`")
        await e.edit("`DI SEMAK SEMAK NGENTOT`")
        await e.edit("`DI KOST-KOSTAN NGENTOT`")
        await e.edit("`DIMANA MANA`")
        await e.edit("`KONTOL KU NGENTOT`")
        await e.edit("`LA LA LA LALALALA`")
        await e.edit("LALALA LA LA LA LA")
        await e.edit("LALALA LA LA LA LA")
        await e.edit("LA LA LA LA")
        await e.edit("LA LA LA LALALALA")
        await e.edit("`LA LA LA LALALALA`")
        await e.edit("LALALA LA LA LA LA LALALALA")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🚶                                 🐢")
        await e.edit("`AHHH MANTAP CROOOOTT`")
        await e.edit("🙉")
        await e.edit("🙈")
        await e.edit("🙉")
        await e.edit("🙈")
        await e.edit("🙉")
        await e.edit("😂")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("`NGENTOT`")


@register(outgoing=True, pattern="^.ig$")
async def usit(e):
    await e.edit(
        "\n[INSTAGRAM](Instagram.com/lutfifirmansyahh)")


@register(outgoing=True, pattern="^.Instagram$")
async def usit(e):
    await e.edit(
        "\n[INSTAGRAM](Instagram.com/dimasary15_)")


@register(outgoing=True, pattern='^.kontol(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`LU SEMUA`")
    sleep(1)
    await typew.edit("`KONTOL`")
    sleep(1)
    await typew.edit("`NGENTOT`")
    sleep(1)
    await typew.edit("`ANJING`")
    sleep(1)
    await typew.edit("`BABI`")
    sleep(1)
    await typew.edit("`KATA UPI`")
# Create by myself @localheart


@register(outgoing=True, pattern="^.mf$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`mf g dl` **ミ(ノ;_ _)ノ=3** ")


@bot.on(events.NewMessage(pattern=r"\.(.*)", outgoing=True))
async def _(event):

    if event.fwd_from:

        return

    animation_interval = 2

    animation_ttl = range(0, 11)

    input_str = event.pattern_match.group(1)

    if input_str == "cinta":

        await event.edit(input_str)

        animation_chars = [
            "`Connecting Ke Server Cinta`",
            "`Mencari Target Cinta`",
            "`Mengirim Cintaku.. 0%\n▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 4%\n█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 8%\n██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 20%\n█████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 36%\n█████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 52%\n█████████████▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 84%\n█████████████████████▒▒▒▒ `",
            "`Mengirim Cintaku.. 100%\n█████████CINTAKU███████████ `",
            f"`Cintaku Sekarang Sepenuhnya Terkirim Padamu, Mau ga jadi pacarku?`"]

        for i in animation_ttl:

            await asyncio.sleep(animation_interval)

            await event.edit(animation_chars[i % 11])


@register(outgoing=True, pattern='^.gombal(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Hai, I LOVE YOU 💞`")
    sleep(1)
    await typew.edit("`I LOVE YOU SO MUCH!`")
    sleep(1)
    await typew.edit("`I NEED YOU!`")
    sleep(1)
    await typew.edit("`I WANT TO BE YOUR BOYFRIEND!`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💕💗`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💗💞`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💝💗`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💟💖`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💘💓`")
    sleep(1)
    await typew.edit("`Tapi Bo'ong`")
# Create by myself @localheart

CMD_HELP.update({
    "gabut":
    "`.ngentot` ; `.jamal`\
    \nUsage: awas ada jamal.\
    \n\n`.dimas`\
    \nUsage: awas ada gondrong\
    \n\n`.ig`\
    \nUsage: Instagram BOSHT\
    \n\n`.instagram`\
    \nUsage: Instagram Dimas\
    \n\n`.gombal`\
    \nUsage: buat bercanda\
    \n\n`.cinta`\
    \nUsage: mengirim cintamu ke seseorang.\
    \n\n`.sayang`\
    \nUsage: untuk jadi buaya.\
    \n\n`.kontol`\
    \nUsage: Lu semua kontol."
})
